###  / \   ### For analysis of real datasets, please use config_template instead.
### / | \  ### The ressources parameters in config_test_evaluation_only.yaml were chosen to use as few ressources as possible for the test dataset
###/  *  \ ### On bigger and more complex datasets, using this config file might lead to crashes

analysis_name: test # Used to name the logs files

##################
##### Inputs #####
##################

### Samples ###
# long reads used for assembly and evaluation
samples: 
 - name: test_dataset
   read_path: test/test_dataset.fastq

# (optional), short reads, may be used for binning or evaluation. Should be from the same sample as the long reads
#short_reads_1: /path/to/short_reads_1.fastq
#short_reads_2: /path/to/short_reads_2.fastq
# (optional), short read assembly, may be used for assembly. Should be from the same sample as the long reads
#short_read_assembly: /path/to/short_read_assembly.fasta

# (optional), long reads used for cobinning. Should be from a similar sample as the studied sample
#additional_reads: 
# - name: sample_name
#   path: /path/to/reads.fastq

# (optional), used for evaluation
#reference_genomes: 
#- /path/to/reference_genome.fasta
#- /path/to/other-reference_genome.fasta
# (optional), used for evaluation a csv with every line following the template "reference_genome_name, group". The names must be the same as the reference genomes files (without the path and extentions), and the groups are arbitrary
#abundance_information: /path/to/abundance.csv #

# (optional), to evaluate bins and assemblies generated by external programs
custom_assembly_path: test/test_assembly.fasta
custom_bins_path: test/test_bins/ # path to a folder containing bins in .fa format


### External programs ###
# (optional), used for evaluation via taxonomic assignation
kraken2db: /projects/genscale/nimauric/databases/standard_kraken_database/ #must be downloaded separately
#gtdbtk_database: /path/to/gtdbtk_release220/ #must be downloaded separately
#mash_database: outputs/mash_db #if doesn't exist, will be created here
checkm_database: outputs/checkm_db/ #if doesn't exist, will be created here

# (optional), for hybrid assembly
#operaMS_path: /path/to/OPERA-MS


####################
##### Controls #####
####################

### Assembly and binning ###
assemblers: # uncomment assemblers to use them
# - metaMDBG
 - custom_assembly # requires custom_assembly_path
# - metaflye
# - hifiasm_meta
# - operaMS # requires short_read_assembly and operaMS_path, performs a hybrid assembly

short_read_binning: false # requires short_reads_1 and short_reads_2
short_read_cobinning: false # requires short_reads_1 and short_reads_2, uses both short and long reads for binning
additional_reads_cobinning: false # requires at least one additional_reads, uses both the long reads, and all additional reads for binning

binning: true
binners: # uncomment binners to use them
#  - metabat2
 - custom # requires custom_bins_path

### Evaluation ###
# contig analysis
metaquast: false # requires reference_genomes
read_mapping_evaluation: true 
short_read_mapping_evaluation: false # requires short_reads_1 and short_reads_2
reference_mapping_evaluation: false # requires reference_genomes

# bins analysis
checkm: true
gtdbtk: false # requires gtdbtk_database and mash_database, analyses all bins
kraken2_on_bins: false #/!\ Require having done binning separatly on a previous step, requires kraken2db, analyses bins specified in kraken2_target_bins
kraken2_target_bins: #/!\ Require having done binning separatly on a previous step, requires kraken2db
 - 1

# Fractionned read analysis
fractions: 
#  - full #all reads
#  - mapped #reads that mapped to a contig, and were sucessfully assembled
  - unmapped #reads that are not mapped to a contig
fastqc: false 
kraken2: true # requires kraken2db
kat: false

#############################
### Functional parameters ###
#############################

read_mapping_threshold: 0 #minimum total alignement length for a read to be considered mapped to a contig
metaquast_min_identity: 95

#############################
### Ressources parameters ###
#############################

# Mapping
rules_mapping: 
  threads: 8
  memory: 2000 
  time: 1*24*60 #in minutes

# Assembly 
rule_metaMDBG_assembly: 
  threads: 8
  memory: 2000 
  time: 2*24*60 #in minutes

rule_metaflye_assembly: 
  threads: 8
  memory: 1600 
  time: 1*24*60 #in minutes

rule_hifiasm_meta_assembly: 
  threads: 8
  memory: 1600 
  time: 2*24*60 #in minutes

rule_operaMS_assembly: 
  threads: 8
  memory: 1000 
  time: 5*24*60 #in minutes

# Binning
rules_metabat2_binnings: 
  threads: 4
  memory: 200
  time: 12*60 #in minutes

# Contig quality analysis
rule_metaquast: 
  threads: 2
  memory: 200 
  time: 24*60 #in minutes

rule_read_contig_mapping_evaluation :
  threads: 2
  memory: 500 
  time: 2*60 #in minutes


# Bin quality analysis
rule_checkm: 
  threads: 4
  memory: 15000
  time: 24*60 #in minutes

rule_checkm_report_writer: 
  threads: 2
  memory: 500 
  time: 1*60 #in minutes

rule_kraken2_on_bins: 
  threads: 2
  memory: 100000 
  time: 4*60 #in minutes

rule_gtdbtk_on_bins: 
  threads: 4
  memory: 50000 
  time: 8*60 #in minutes

rule_read_contig_mapping_plot:
  threads: 2
  memory: 300
  time: 2*60 #in minutes

  
# read quality analysis 
rule_extract_unmapped_reads: 
  threads: 4
  memory: 500 
  time: 24*60 #in minutes

rule_kraken2: 
  threads: 2
  memory: 100000 
  time: 4*60 #in minutes

rule_kat_sect: 
  threads: 2
  memory: 2000 
  time: 4*60 #in minutes

rule_fastqc: 
  threads: 2
  memory: 50
  time: 2*60 #in minutes