analysis_name: analysis_name # Used to name the logs files

##### Inputs #####
### Samples ###
# long reads used for assembly and evaluation
samples: 
 - name: sample_name
   read_path: /path/to/reads.fastq

# (optional), short reads, may be used for binning or evaluation. Should be from the same sample as the long reads
short_reads_1: /path/to/short_reads_1.fastq
short_reads_2: /path/to/short_reads_2.fastq
# (optional), short read assembly, may be used for assembly. Should be from the same sample as the long reads
short_read_assembly: /path/to/short_read_assembly.fasta

# (optional), long reads used for cobinning. Should be from a similar sample as the studied sample
additional_reads: 
 - name: sample_name
   path: /path/to/reads.fastq

# (optional), used for evaluation
reference_genomes: 
- /path/to/reference_genome.fasta
# (optional), used for evaluation a csv with every line following the template "reference_genome_name, group". The names must be the same as the reference genomes files (without the path and extentions), and the groups are arbitrary
abundance_information: /path/to/abundance.csv #

# (optional), to evaluate bins and assemblies generated by external programs
custom_assembly_path: path/to/assembly.fasta
custom_bins_path: path/to/bins/ # path to a folder containing bins in .fa format


### External programs ###
# (optional), used for evaluation via taxonomic assignation
kraken2db: /path/to/kraken_database/ #must be downloaded separately
gtdbtk_database: /path/to/gtdbtk_release220/ #must be downloaded separately
mash_database: outputs/mash_db #if doesn't exist, will be created here
checkm_database: outputs/checkm_db/ #if doesn't exist, will be created here

# (optional), for hybrid assembly
operaMS_path: /path/to/OPERA-MS


##### Controls #####
### Assembly and binning ###
assemblers: # uncomment assemblers to use them
 - metaMDBG
# - custom_assembly # requires custom_assembly_path
 - metaflye
 - hifiasm_meta
# - operaMS # requires short_read_assembly and operaMS_path, performs a hybrid assembly

short_read_binning: false # requires short_reads_1 and short_reads_2
short_read_cobinning: false # requires short_reads_1 and short_reads_2, uses both short and long reads for binning
additional_reads_cobinning: false # requires at least one additional_reads, uses both the long reads, and all additional reads for binning

binning: true
binners: # uncomment binners to use them
  - metabat2
# - custom # requires custom_bins_path

### Evaluation ###
# contig analysis
metaquast: false # requires reference_genomes
read_mapping_evaluation: true 
short_read_mapping_evaluation: false # requires short_reads_1 and short_reads_2
reference_mapping_evaluation: false # requires reference_genomes

# bins analysis
checkm: true
gtdbtk: true # requires gtdbtk_database and mash_database, analyses all bins
kraken2_on_bins: false #/!\ Require having done binning separatly on a previous step, requires kraken2db, analyses bins specified in target_bins
target_bins: #/!\ Require having done binning separatly on a previous step, requires kraken2db
 - 1

# Fractionned read analysis
fractions: 
#  - full #all reads
  - mapped #reads that mapped to a contig, and were sucessfully assembled
  - unmapped #reads that are not mapped to a contig
fastqc: true 
kraken2: true # requires kraken2bin; kraken2db and kronabin
kat: true

##### Parameters #####
### Functional parameters ###
read_mapping_threshold: 0 #minimum total alignement length for a read to be considered mapped to a contig
metaquast_min_identity: 95

### Ressources parameters ###

# Mapping
rules_mapping: 
  threads: 24
  memory: 50000 
  time: 1*24*60 #in minutes

# Assembly 
rule_metaMDBG_assembly: 
  threads: 48
  memory: 35000 
  time: 2*24*60 #in minutes

rule_metaflye_assembly: 
  threads: 48
  memory: 160000 
  time: 1*24*60 #in minutes

rule_hifiasm_meta_assembly: 
  threads: 48
  memory: 160000 
  time: 2*24*60 #in minutes

rule_operaMS_assembly: 
  threads: 48
  memory: 100000 
  time: 5*24*60 #in minutes

# Binning
rules_metabat2_binnings: 
  threads: 16
  memory: 20000 
  time: 12*60 #in minutes

# Contig quality analysis
rule_metaquast: 
  threads: 1
  memory: 20000 
  time: 24*60 #in minutes

rule_read_contig_mapping_evaluation :
  threads: 1
  memory: 10000 
  time: 2*60 #in minutes


# Bin quality analysis
rule_checkm: 
  threads: 16
  memory: 50000 
  time: 24*60 #in minutes

rule_checkm_report_writer: 
  threads: 1
  memory: 50000 
  time: 1*60 #in minutes

rule_kraken2_on_bins: 
  threads: 12
  memory: 100000 
  time: 4*60 #in minutes

rule_gtdbtk_on_bins: 
  threads: 20
  memory: 100000 
  time: 8*60 #in minutes

rule_read_contig_mapping_plot:
  threads: 1
  memory: 30000 
  time: 2*60 #in minutes

  
# read quality analysis 
rule_extract_unmapped_reads: 
  threads: 24
  memory: 50000 
  time: 24*60 #in minutes

rule_kraken2: 
  threads: 12
  memory: 100000 
  time: 4*60 #in minutes

rule_kat_sect: 
  threads: 12
  memory: 200000 
  time: 4*60 #in minutes

rule_fastqc: 
  threads: 1
  memory: 5000 
  time: 2*60 #in minutes